**Assignment on NumPy**

In [ ]:
import numpy as np

1. Write a NumPy program to get the NumPy version and show NumPy build
configuration. 


In [ ]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2. Write a NumPy program to get help on the add function. 


In [ ]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

3. Write a NumPy program to test whether none of the elements of a given array is zero. 


In [ ]:
arr = [0, 1, 2, 3, 4]
print("Test if none of the elemnts is zero: ", end="")
print(np.all(arr))

arr = [1, 2, 3, 4]
print("Test if none of the elemnts is zero: ", end="")
print(np.all(arr))

Test if none of the elemnts is zero: False
Test if none of the elemnts is zero: True


4. Write a NumPy program to test whether any of the elements of a given array is nonzero. 


In [ ]:
arr = [0, 0, 0, 0]
print("Test if any of the elemnts is non-zero: ", end="")
print(np.any(arr))

arr = [1, 2, 3, 4]
print("Test if any of the elemnts is non-zero: ", end="")
print(np.any(arr))

Test if any of the elemnts is non-zero: False
Test if any of the elemnts is non-zero: True


5. Write a NumPy program to test a given array elementwise for finiteness (not infinity
or not a Number). 

In [ ]:
arr = np.array([np.nan, np.inf, 0, 3, 4, 5])
print(np.isfinite(arr))

[False False  True  True  True  True]


6. Write a NumPy program to test elementwise for positive or negative infinity.

In [ ]:
arr = np.array([np.nan, np.inf, 0, 3, 4, 5])
print(np.isinf(arr))

[False  True False False False False]


7. Write a NumPy program to test elementwise for NaN (Not a Number) of a given
array

In [ ]:
arr = np.array([np.nan, np.inf, 0, 3, 4, 5])
print(np.isnan(arr))

[ True False False False False False]


8. Write a NumPy program to test elementwise for complex number, real number of a
given array. Also test whether a given number is a scalar type or not. 


In [ ]:
arr = np.array([5.7, 2+7j, 9j, 0, 3])
print(np.iscomplex(arr))
print(np.isreal(arr))
print(np.isscalar(544))
print(np.isscalar(544j))
print(np.isscalar([544]))


[False  True  True False False]
[ True False False  True  True]
True
True
False


9. Write a NumPy program to test whether two arrays are element-wise equal within a
tolerance 

In [38]:
print(np.allclose(2.5, 2.4))
print(np.allclose(1, 0.9999999))
arr1 = np.array([5e5, 1e-7, 4.000004e6])
arr2 = np.array([5.00001e5, 1e-7, 4e6])
np.allclose(arr1, arr2)

False
True


True

10. Write a NumPy program to create an element-wise comparison (greater, greater
equal, less and less equal) of two given arrays 


In [42]:
arr1 = np.array([9, 6])
arr2 = np.array([4, 8])
print(np.greater(arr1, arr2))
print(np.greater_equal(arr1, arr2))
print(np.less(arr1, arr2))
print(np.less_equal(arr1, arr2))

[ True False]
[ True False]
[False  True]
[False  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within
a tolerance) of two given arrays. 


In [44]:
arr1 = np.array([96, 24, 25, 50])
arr2 = np.array([96, 24, 25, 50.000001])
print(np.equal(arr1, arr2))
print(np.allclose(arr1, arr2))

[ True  True  True False]
True


12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and
determine the size of the memory occupied by the array

In [47]:
arr = np.array([1, 7, 13, 105])
print(arr)
print(arr.size * arr.itemsize, end=" ")
print("Bytes")

[  1   7  13 105]
32 Bytes


13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives. 


In [51]:
arr1 = np.zeros(10)
print(arr1)
arr2 = np.ones(10)
print(arr2)
arr3 = np.ones(10) * 5
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of the integers from 30 to70 


In [52]:
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15. Write a NumPy program to create an array of all the even integers from 30 to 70. 


In [53]:
print(np.arange(30, 71, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Write a NumPy program to create a 3x3 identity matrix

In [54]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Write a NumPy program to generate a random number between 0 and 1. 

In [65]:
number = np.random.normal(0,1,1)
print(number)

[0.75352641]


18. Write a NumPy program to generate an array of 15 random numbers from a standard
normal distribution

In [66]:
arr = np.random.normal(0, 1, 15)
print(arr)

[-1.01566408  1.96952427  1.2423678   1.30330667 -0.24673329 -0.83731377
 -0.20950208  0.40347485 -1.19909039 -0.4628677  -1.10748636  1.33421181
  0.69908094  0.35784837  1.12786728]


19. Write a NumPy program to create a vector with values ranging from 15 to 55 and
print all values except the first and last. 


In [67]:
arr = np.arange(15, 56)
print(arr)
print(arr[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20. Write a NumPy program to create a 3X4 array using and iterate over it. 


In [70]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
for i in np.nditer(arr):
  print(i, end = " ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

21. Write a NumPy program to create a vector of length 10 with values evenly
distributed between 5 and 50. 


In [72]:
arr = np.linspace(5, 50, 10 )
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


22. Write a NumPy program to create a vector with values from 0 to 20 and change the
sign of the numbers in the range from 9 to 15 


In [75]:
arr = np.arange(0, 21)
print(arr)
for i in range(21):
  if (9 <= arr[i] <= 15):
    arr[i] = arr[i] * -1
print(arr)

# OR
# x[(x >= 9) & (x <= 15)] *= -1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers
from 0 to 10. 


In [76]:
print(np.random.randint(0, 11, 5))

[5 6 6 1 2]


24. Write a NumPy program to multiply the values of two given vectors. 

In [80]:
arr1 = np.arange(1, 6)
arr2 = np.arange(6, 11)
print(arr1)
print(arr2) 
print(arr1 * arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 6 14 24 36 50]
